### ISSUE TITLE
Discount and Coupon system

### ISSUE THREAD

**Issue by chmkai** [chmkai/superman#10]
Discount and coupon system needed
Make the relevant changes in `invman.*`,`invoice.*` and `items.*`

**Comment by BlackWolf1937** [comment]
Lets have some predefined codes... like "BXA#15%Free!!#"  "BXA#50%discnt#"   "BXA#12%offer!#" etc..
Then simply have the codes tested and if true, gives discount (eg. "BXA#15%Free!!#"  gives 15% discount......... obviously.. ) and then just calculate the reduced prices...


**NOTE** 
Don't lets use such painfully obvious codes... I couldn't think of a better code on the spur of the moment... 
Also 
Managers will be able to cancel any code anytime they want... we can use that if some of the codes cause errors
So there should be a message to inform code is "invalid" or "has been cancelled"

**Comment by BlackWolf1937** [comment]
so we could do something like let the person type in different code and find out that they've been **CANCELLED**    
:trollface:

**Comment by chmkai** [comment]
> Lets have some predefined codes... like "BXA#15%Free!!#" "BXA#50%discnt#" "BXA#12%offer!#" etc..
Then simply have the codes tested and if true, gives discount (eg. "BXA#15%Free!!#" gives 15% discount......... obviously.. ) and then just calculate the reduced prices...

@BlackWolf1937 , I think we could have something like that which could be interpreted by the system, but instead of showing a code like that directly (too easily modified), we could bitwise XOR (eg.`A ^ B`) the string and have the coupon code be a string of (hexadec.?) numbers .

The conversion would be like [ BX#15%F  <--->  b'G]&40 C'  <---> 475d2634302043]
