### ISSUE TITLE
Floating-point error in `invman.cpp`

### ISSUE THREAD

**Issue by chmkai** [chmkai/superman#8]
The `Price` coloumn in the "StockList" `Listbox` shows two `0`s after the decimal point, regardless of the actual digits to the right of the decimal point.

**Comment by chmkai** [comment]
(Possible Rounding error somewhere?)
Suspect problem with `atof()` function(?)

**Comment by BlackWolf1937** [comment]
If its just 2 0s after the decimal, its nothing to worry about 
i.e. if its like --> 245=>245.00 && 245.75=>245.75
If its not like that could you leave an example?

**Comment by chmkai** [comment]
> If its just 2 0s after the decimal, its nothing to worry about
i.e. if its like --> 245=>245.00 && 245.75=>245.75
If its not like that could you leave an example?

@BlackWolf1937 , it's more like:
```
245 => 245.00
245.75 => 245.00
245.245 => 245.00
```
